version: "3.9"

services:
  app:
    build: .
    container_name: url-shortener-app
    expose:
      - "3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  urlshortener_db: